###############################################################################
#
#  Makefile
#
#  hmap Makefile
#
###############################################################################
MODULE :=  hmap
AUTOMODULE :=  hmap

ifndef BUILDER
$(error Please set the $$BUILDER variable)
endif

include $(BUILDER)/definemodule.mk
