###############################################################################
#
#  hmap Unit Testing Module Makefile
#
#  
#
###############################################################################
MODULE := hmap_utest
NOMODULEMAKE := 1
TEST_MODULE :=  hmap
PEDANTIC := 1
DEPENDMODULES := AIM
include ../make/utestmodule.mk
